//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCards
    {
        public int GiftCardID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public Nullable<decimal> InitialBalance { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
