//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoicePosition = new HashSet<InvoicePosition>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> ContractorID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePosition> InvoicePosition { get; set; }
    }
}
